import os 
from dotenv import load_dotenv

load_dotenv()
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
HF_TOKEN = os.getenv('HF_TOKEN')

locations=['Indonesia','China', 'England','Japan','Egypt','Germany']
locations=['Indonesia','China', 'England','Japan','Egypt','Germany']

england_sub_topics=['breakfast','dinner','traditional foods and beverages','cutlery','cooking ware', 'fruit', 'food souvenirs', 'snacks',
               'wedding location', 'wedding dowry', 'traditions before marriage', 'traditions when getting married', 'traditions after marriage', 
               'men’s wedding clothes', 'women’s wedding clothes', 'songs and activities during the wedding', 'invited guests at a wedding', 'gift brought to weddings', 'food at a wedding',
                'eating habit', 'greetings habits', 'financial habits (saving, debit/credit)', 'punctuality habits', 'cleanliness habits', 'shower time habits', 'transportation habits', 
                'popular sports','musical instruments', 'folks songs', 'traditional dances', 'use of art at certain events', 'poetry or similar literature',
               'morning activities', 'afternoon activities', 'evening activities', 'Leisure and relaxation activities', 'Household activities (cleaning, home management)',
                 'relationships within the main family', 'relationships in the extended family', 'relations with society/neighbors', 'clan/descendant system',
                 'traditions during pregnancy', 'traditions after birth', 'how to care for a newborn baby', 'how to care for toddlers', 'how to care for teenagers', 'parents and children interactions as adults', 'when death occurs', 'the process of dealing with a corpse', 'traditions after the body is buried', 'the clothes of the mourners','inheritance matters',
                'traditions before religious holidays', 'traditions leading up to religious holidays', 'traditions during religious holidays', 'traditions after holidays',
               'traditional game types','regular religious activities', 'mystical things', 'traditional ceremonies', 'lifestyle', 'self care', 'traditional medicine', 'traditional sayings']

chinese_monolingual_sutopics=['breakfast','dinner','traditional foods and beverages','cutlery','cooking ware', 'fruit', 'food souvenirs', 'snacks',
                'wedding location', 'wedding dowry', 'traditions before marriage', 'traditions when getting married', 'traditions after marriage', 
                'men’s wedding clothes', 'women’s wedding clothes', 'songs and activities during the wedding', 'invited guests at a wedding', 'gift brought to weddings', 'food at a wedding',
                 'eating habit', 'greetings habits', 'financial habits (saving, debit/credit)', 'punctuality habits', 'cleanliness habits', 'shower time habits', 'transportation habits', 
                 'popular sports','musical instruments', 'folks songs', 'traditional dances', 'use of art at certain events', 'poetry or similar literature',
                'morning activities', 'afternoon activities', 'evening activities', 'Leisure and relaxation activities', 'Household activities (cleaning, home management)',
                  'relationships within the main family', 'relationships in the extended family', 'relations with society/neighbors', 'clan/descendant system',
                  'traditions during pregnancy', 'traditions after birth', 'how to care for a newborn baby', 'how to care for toddlers', 'how to care for teenagers', 'parents and children interactions as adults','when death occurs', 'the process of dealing with a corpse', 'traditions after the body is buried', 'the clothes of the mourners','inheritance matters', 'traditions before traditional holidays','traditions leading up to traditional holidays','traditions during traditional holidays',  'traditions after holidays',
                 'traditional game types', 'mystical things', 'traditional ceremonies', 'lifestyle', 'self care', 'traditional medicine', 'traditional sayings']

japanese_monolingual_sutopics=['breakfast','dinner','traditional foods and beverages','cutlery','cooking ware', 'fruit', 'food souvenirs', 'snacks',
                'wedding location', 'wedding dowry', 'traditions before marriage', 'traditions when getting married', 'traditions after marriage', 
                'men’s wedding clothes', 'women’s wedding clothes', 'songs and activities during the wedding', 'invited guests at a wedding', 'gift brought to weddings', 'food at a wedding',
                 'eating habit', 'greetings habits', 'financial habits (saving, debit/credit)', 'punctuality habits', 'cleanliness habits', 'shower time habits', 'transportation habits', 
                 'popular sports','musical instruments', 'folks songs', 'traditional dances', 'use of art at certain events', 'poetry or similar literature',
                'morning activities', 'afternoon activities', 'evening activities', 'Leisure and relaxation activities', 'Household activities (cleaning, home management)',
                  'relationships within the nuclear family', 'relationships in the extended family', 'relations with society/neighbors', 'clan/descendant system',
                  'traditions during pregnancy', 'traditions after birth', 'how to care for a newborn baby', 'how to care for toddlers', 'how to care for junior high or high school kids', 'parents and children interactions as adults','when death occurs', 'the process of dealing with a corpse', 'traditions after the funeral', 'the clothes of the mourners','inheritance matters', 'traditions before traditional holidays','traditions leading up to traditional holidays','traditions during traditional holidays',  'traditions after holidays',
                 'traditional game types', 'regular religious activities', 'mystical things', 'traditional ceremonies', 'lifestyle', 'self care', 'traditional medicine', 'traditional sayings']

indonesia_sub_topics=['Sarapan','Makan malam','Makanan dan minuman tradisional','Peralatan makanan','Peralatan masak','Buah-buahan', 'Buah tangan (makanan)','Makanan ringan','Lokasi pernikahan','Mahar / mas kawin','Tradisi sebelum menikah','Tradisi ketika menikah','Tradisi setelah menikah','Pakaian pernikahan pengantin pria','Pakaian pernikahan pengantin wanita','Lagu dan aktivitas selama pernikahan','Tamu-tamu yang diundang ke pernikahan','Hadiah yang dibawa ke pernikahan','Makanan hidangan pernikahan','Kebiasaan ketika makan','Kebiasaan saat bertemu orang lain','Kebiasaan finansial','Kebiasaan ketepatan waktu','kebiasaan bersih-bersih','kebiasaan waktu mandi','kebiasaan dalam transportasi','Olah raga populer','Instrumen musik','Lagu daerah','Tarian tradisional','Pertunjukan seni pada acara tertentu','Puisi atau literatur serupa','Aktivitas di pagi hari','Aktivitas di sore hari','Aktivitas di malam hari','Aktivitas di waktu santai','Aktivitas rumah tangga','hubungan dengan keluarga inti','hubungan dengan keluarga besar','hubungan dengan tetangga','sistem suku atau keturunan','tradisi ketika masa kehamilan','tradisi setelah lahiran','cara mengurus bayi baru lahir','cara mengurus balita','cara mengurus anak remaja','Interaksi orang tua dan anak yang sudah dewasa','Ketika kematian terjadi','Proses penanganan jenazah','Tradisi ketika jenazah dimakamkan','Baju pelayat','Perkara warisan','Tradisi sebelum hari besar agama','Tradisi menjelang hari besar agama','Tradisi saat hari besar agama','Tradisi setelah liburan','Jenis-jenis permainan tradisional','Aktivitas agama','Hal-hal mistis','Perayaan/upacara tradisional','Gaya hidup','Perawatan diri','Obat tradisional','Pepatah tradisional']

chinese_sub_topics=['早饭','晚饭','传统的食物和饮料','食具','炊具','水果','可食用的纪念品','零食','婚礼地点','嫁妆彩礼','结婚前的传统','结婚时的传统','结婚后的传统','男士的婚礼服饰','女士的婚礼服饰','婚礼期间的音乐和活动','婚礼的宾客','婚礼的礼物','婚礼上的食物','饮食习惯','问候习惯','财务习惯（储蓄、借记/贷记）','时间观念','清洁习惯','淋浴时间习惯','交通习惯','流行运动','乐器','民谣','传统舞蹈','在某些活动中使用艺术形式','诗歌或其他文学','晨间活动','下午活动','晚间活动','休闲和放松活动','家庭活动（清洁、家庭管理）','家庭内部的关系','大家庭中的关系','与社会/邻居的关系','氏族/后裔系统','怀孕期间的传统','出生后的传统','如何照顾新生婴儿','如何照顾幼儿','如何照顾青少年','父母和孩子像成年人一样互动','当死亡发生时','处理尸体的过程','遗体下葬后的传统','哀悼者的衣服','继承问题','传统节日之前的习俗','传统节日之前的准备习俗','传统节日中的习俗','传统节日之后的习俗','传统游戏类型','神秘的东西','传统仪式','生活方式','自理','传统医学','传统俗语']

japan_sub_topics=['朝食','夕食','伝統的な食べ物や飲み物','食器用具','調理器具','果物','食べ物のお土産','おやつ','結婚式場','結納金','結婚前の慣例','結婚時の慣例','結婚後の慣例','新郎の婚礼衣装','新婦の婚礼衣装','結婚式中の歌やイベント','結婚式の来賓','結婚祝い','結婚式の料理','食事の習慣','挨拶の習慣','お金の習慣（貯蓄、貸借)','時間を守る習慣','衛生に関する習慣','入浴習慣','交通に関する習慣','人気なスポーツ','楽器','民謡','伝統舞踊','イベントにおける芸術の利用','詩または類似する文学','朝の活動','午後の活動','夜の活動','余暇およびリラクゼーション活動','家事（掃除、家庭管理）','核家族内の関係','拡大家族内の関係','社会的および隣人関係','家系・系譜','妊娠中のならわし','産後のならわし','新生児の育て方','幼児の育て方','中高生の育て方','大人としての親子関係','人が亡くなった時','遺体の処理','葬儀時の伝統','喪服','相続問題','伝統的休日の前の慣例','伝統的休日までの慣例','伝統的休日中の慣例','休日後の慣例','伝統的な遊び','宗教的な日常活動','神秘的な物事','伝統儀式','生活様式','自己管理','伝統医学','ことわざ']
egypt_sub_topics=['إفطار','عشاء','الأطعمة والمشروبات التقليدية','أدوات المائدة','أواني الطبخ','فاكهة','هدايا تذكارية غذائية','وجبات خفيفة','موقع الزفاف','مهر الزواج','التقاليد قبل الزواج','التقاليد عند الزواج','التقاليد بعد الزواج','ملابس الزفاف للرجال','ملابس الزفاف للنساء','الأغاني والأنشطة أثناء الزفاف','الضيوف المدعوون في الزفاف','الهدايا المقدمة في الزفاف','الطعام في الزفاف','عادات الأكل','عادات التحية','العادات المالية (الادخار، الديون/الائتمان)','عادات الالتزام بالمواعيد','عادات النظافة','عادات وقت الاستحمام','عادات التنقل','الرياضات الشعبية','الآلات الموسيقية','الأغاني الشعبية','الرقصات التقليدية','استخدام الفن في أحداث معينة','الشعر أو الأدب المماثل','أنشطة الصباح','أنشطة بعد الظهر','أنشطة المساء','أنشطة الترفيه والاسترخاء','أنشطة المنزل (التنظيف، إدارة المنزل)','العلاقات داخل الأسرة الرئيسية','العلاقات في الأسرة الممتدة','العلاقات مع المجتمع/الجيران','نظام العشيرة/النسل','التقاليد أثناء الحمل','التقاليد بعد الولادة','كيفية رعاية المولود الجديد','كيفية رعاية الأطفال الصغار','كيفية رعاية المراهقين','تفاعلات الآباء والأبناء كبالغين','عند حدوث الوفاة','عملية التعامل مع الجثمان','التقاليد بعد دفن الجثمان','ملابس المعزين','مسائل الميراث','التقاليد قبل الأعياد الدينية','التقاليد التي تسبق الأعياد الدينية','التقاليد أثناء الأعياد الدينية','التقاليد بعد الأعياد','أنواع الألعاب التقليدية','الأنشطة الدينية العادية','الأشياء الغامضة','الاحتفالات المحلية','أسلوب الحياة','العناية بالنفس','الطب التقليدي','الأمثال التقليدية']
germany_sub_topics=['Frühstück','Abendessen','Traditionelle Speisen und Getränke','Besteck','Kochgeschirr','Obst','Kulinarische Souvenirs','Snacks','Hochzeitsort','Hochzeitsaussteuer','Traditionen vor der Ehe','Traditionen bei der Eheschließung','Traditionen nach der Ehe','Hochzeitskleidung der Männer','Hochzeitskleidung der Frauen','Lieder und Aktivitäten während der Hochzeit','Eingeladene Gäste bei einer Hochzeit','Hochzeitsgeschenk','Essen bei einer Hochzeit','Essgewohnheiten','Begrüßungsgewohnheiten','Finanzgewohnheiten (Sparen, Debit/Kredit)','Pünktlichkeitsgewohnheiten','Sauberkeitsgewohnheiten','Duschgewohnheiten','Transportgewohnheiten','Beliebte Sportarten','Musikinstrumente','Volkslieder','Traditionelle Tänze','Verwendung von Kunst bei bestimmten Anlässen','Poesie oder ähnliche Literatur','Morgenaktivitäten','Nachmittagsaktivitäten','Abendaktivitäten','Freizeit- und Entspannungsaktivitäten','Haushaltsaktivitäten (Reinigung, Haushaltsführung)','Beziehungen innerhalb der Kernfamilie','Beziehungen in der erweiterten Familie','Beziehungen zur Gesellschaft/Nachbarn','Klan-/Abstammungssystem','Traditionen während der Schwangerschaft','Traditionen nach der Geburt','Wie man sich um ein Neugeborenes kümmert','Wie man sich um Kleinkinder kümmert','Wie man sich um Teenager kümmert','Interaktionen zwischen Eltern und Kindern als Erwachsene','Beim Todesfall','Der Prozess des Umgangs mit einem Leichnam','Traditionen nach der Beerdigung','Die Kleidung der Trauernden','Erbschaftsangelegenheiten','Traditionen vor religiösen Feiertagen','Traditionen im Vorfeld der religiösen Feiertage','Traditionen während religiöser Feiertage','Traditionen nach Feiertagen','Arten von traditionellen Spielen','Regelmäßige religiöse Aktivitäten','Mystische Dinge','Traditionelle Zeremonien','Lebensstil','Selbstfürsorge','Traditionelle Medizin','Traditionelle Sprichwörter']

location_in_local_language={'Indonesia':'Indonesia','China':'中国','England':'England','Japan':'日本','Germany':'Deutschland','Egypt':'مصر'}
location_to_language={'England':'English','Indonesia':'Bahasa Indonesia','Japan':'日本語','Germany':'Deutsch',
                      'Egypt':' اللغة العربية الفصحى','China':'中文'}
sub_topics_in_local_language_per_location={'England':england_sub_topics,'Indonesia':indonesia_sub_topics,
                                           'Japan':japan_sub_topics,'China':chinese_sub_topics,'Egypt':egypt_sub_topics,
                                           'Germany':germany_sub_topics}
